# **Hyperparameter tuning in sklearn**

In Machine Learning, a **hyperparameter** is a parameter of a ML model whose value is used to customize the learning algorithm.

Typically, every application domain, or even every single problem, has a optimum set of hyperparameters values that provide the best performance for the selected model on that problem or dataset.

The best hyperparameters values can not be extracted from the dataset characteristics, all that you have is your experience and some heuristics. Therefore, **automation toolkits that boost the hyperparameters search** are a key resource for the ML engineer. `GridSearchCV` and `RandomizedSearchCV` are the `sklearn` packages for that purpose.

## Import Library

In [ ]:
!pip install --upgrade openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl) (2.0.0)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import data from the dataset

In [ ]:
# upload files from your local machine
#from google.colab import files
#files.upload()
dataset = pd.read_excel('Ensayo_Motores_rpm_par.xlsx')
X = dataset.iloc[:, [1,2]].values
y = dataset.iloc[:, 3].values

In [ ]:
# explore dataset
np.set_printoptions(formatter={'float': '{:0.2f}'.format})
print(X)
print(y)
dataset.info()
dataset.head(10)

[[19.00 19000.00]
 [35.00 20000.00]
 [26.00 43000.00]
 [27.00 57000.00]
 [19.00 76000.00]
 [27.00 58000.00]
 [27.00 84000.00]
 [32.00 150000.00]
 [25.00 33000.00]
 [35.00 65000.00]
 [26.00 80000.00]
 [26.00 52000.00]
 [20.00 86000.00]
 [32.00 18000.00]
 [18.00 82000.00]
 [29.00 80000.00]
 [47.00 25000.00]
 [45.00 26000.00]
 [46.00 28000.00]
 [48.00 29000.00]
 [45.00 22000.00]
 [47.00 49000.00]
 [48.00 41000.00]
 [45.00 22000.00]
 [46.00 23000.00]
 [47.00 20000.00]
 [49.00 28000.00]
 [47.00 30000.00]
 [29.00 43000.00]
 [31.00 18000.00]
 [31.00 74000.00]
 [27.00 137000.00]
 [21.00 16000.00]
 [28.00 44000.00]
 [27.00 90000.00]
 [35.00 27000.00]
 [33.00 28000.00]
 [30.00 49000.00]
 [26.00 72000.00]
 [27.00 31000.00]
 [27.00 17000.00]
 [33.00 51000.00]
 [35.00 108000.00]
 [30.00 15000.00]
 [28.00 84000.00]
 [23.00 20000.00]
 [25.00 79000.00]
 [27.00 54000.00]
 [30.00 135000.00]
 [31.00 89000.00]
 [24.00 32000.00]
 [18.00 44000.00]
 [29.00 83000.00]
 [35.00 23000.00]
 [27.00 58000.00]
 [24.00 55000.00]
 [23.00 48000.00]
 [28.00 79000.00]
 [22.00 18000.00]
 [32.00 117000.00]
 [27.00 20000.00]
 [25.00 87000.00]
 [23.00 66000.00]
 [32.00 120000.00]
 [59.00 83000.00]
 [24.00 58000.00]
 [24.00 19000.00]
 [23.00 82000.00]
 [22.00 63000.00]
 [31.00 68000.00]
 [25.00 80000.00]
 [24.00 27000.00]
 [20.00 23000.00]
 [33.00 113000.00]
 [32.00 18000.00]
 [34.00 112000.00]
 [18.00 52000.00]
 [22.00 27000.00]
 [28.00 87000.00]
 [26.00 17000.00]
 [30.00 80000.00]
 [39.00 42000.00]
 [20.00 49000.00]
 [35.00 88000.00]
 [30.00 62000.00]
 [31.00 118000.00]
 [24.00 55000.00]
 [28.00 85000.00]
 [26.00 81000.00]
 [35.00 50000.00]
 [22.00 81000.00]
 [30.00 116000.00]
 [26.00 15000.00]
 [29.00 28000.00]
 [29.00 83000.00]
 [35.00 44000.00]
 [35.00 25000.00]
 [28.00 123000.00]
 [35.00 73000.00]
 [28.00 37000.00]
 [27.00 88000.00]
 [28.00 59000.00]
 [32.00 86000.00]
 [33.00 149000.00]
 [19.00 21000.00]
 [21.00 72000.00]
 [26.00 35000.00]
 [27.00 89000.00]
 [26.00 86000.00]
 [38.00 80000.00]
 [39.00 71000.00]
 [37.00 71000.00]
 [38.00 61000.00]
 [37.00 55000.00]
 [42.00 80000.00]
 [40.00 57000.00]
 [35.00 75000.00]
 [36.00 52000.00]
 [40.00 59000.00]
 [41.00 59000.00]
 [36.00 75000.00]
 [37.00 72000.00]
 [40.00 75000.00]
 [35.00 53000.00]
 [41.00 51000.00]
 [39.00 61000.00]
 [42.00 65000.00]
 [26.00 32000.00]
 [30.00 17000.00]
 [26.00 84000.00]
 [31.00 58000.00]
 [33.00 31000.00]
 [30.00 87000.00]
 [21.00 68000.00]
 [28.00 55000.00]
 [23.00 63000.00]
 [20.00 82000.00]
 [30.00 107000.00]
 [28.00 59000.00]
 [19.00 25000.00]
 [19.00 85000.00]
 [18.00 68000.00]
 [35.00 59000.00]
 [30.00 89000.00]
 [34.00 25000.00]
 [24.00 89000.00]
 [27.00 96000.00]
 [41.00 30000.00]
 [29.00 61000.00]
 [20.00 74000.00]
 [26.00 15000.00]
 [41.00 45000.00]
 [31.00 76000.00]
 [36.00 50000.00]
 [40.00 47000.00]
 [31.00 15000.00]
 [46.00 59000.00]
 [29.00 75000.00]
 [26.00 30000.00]
 [32.00 135000.00]
 [32.00 100000.00]
 [25.00 90000.00]
 [37.00 33000.00]
 [35.00 38000.00]
 [33.00 69000.00]
 [18.00 86000.00]
 [22.00 55000.00]
 [35.00 71000.00]
 [29.00 148000.00]
 [29.00 47000.00]
 [21.00 88000.00]
 [34.00 115000.00]
 [26.00 118000.00]
 [34.00 43000.00]
 [34.00 72000.00]
 [23.00 28000.00]
 [35.00 47000.00]
 [25.00 22000.00]
 [24.00 23000.00]
 [31.00 34000.00]
 [26.00 16000.00]
 [31.00 71000.00]
 [32.00 117000.00]
 [33.00 43000.00]
 [33.00 60000.00]
 [31.00 66000.00]
 [20.00 82000.00]
 [33.00 41000.00]
 [35.00 72000.00]
 [28.00 32000.00]
 [24.00 84000.00]
 [19.00 26000.00]
 [29.00 43000.00]
 [19.00 70000.00]
 [28.00 89000.00]
 [34.00 43000.00]
 [30.00 79000.00]
 [20.00 36000.00]
 [26.00 80000.00]
 [35.00 22000.00]
 [35.00 39000.00]
 [49.00 74000.00]
 [39.00 134000.00]
 [41.00 71000.00]
 [58.00 101000.00]
 [47.00 47000.00]
 [55.00 130000.00]
 [52.00 114000.00]
 [40.00 142000.00]
 [46.00 22000.00]
 [48.00 96000.00]
 [52.00 150000.00]
 [59.00 42000.00]
 [35.00 58000.00]
 [47.00 43000.00]
 [60.00 108000.00]
 [49.00 65000.00]
 [40.00 78000.00]
 [46.00 96000.00]
 [59.00 143000.00]
 [41.00 80000.00]
 [35.00 91000.00]
 [37.00 144000.00]
 [60.00 102000.00]
 [35.00 60000.00]
 [37.00 53000.00]
 [36.00 126000.00]
 [56.00 133000.00]
 [40.00 72000.00]
 [42.00 80000.00]
 [35.00 147000.00]
 [39.00 42000.00]
 [40.00 107000.00]
 [49.00 86000.00]
 [38.00 112000.00]
 [46.00 79000.00]
 [40.00 57000.00]
 [37.00 80000.00]
 [46.00 82000.00]
 [53.00 143000.00]
 [42.00 149000.00]
 [38.00 59000.00]
 [50.00 88000.00]
 [56.00 104000.00]
 [41.00 72000.00]
 [51.00 146000.00]
 [35.00 50000.00]
 [57.00 122000.00]
 [41.00 52000.00]
 [35.00 97000.00]
 [44.00 39000.00]
 [37.00 52000.00]
 [48.00 134000.00]
 [37.00 146000.00]
 [50.00 44000.00]
 [52.00 90000.00]
 [41.00 72000.00]
 [40.00 57000.00]
 [58.00 95000.00]
 [45.00 131000.00]
 [35.00 77000.00]
 [36.00 144000.00]
 [55.00 125000.00]
 [35.00 72000.00]
 [48.00 90000.00]
 [42.00 108000.00]
 [40.00 75000.00]
 [37.00 74000.00]
 [47.00 144000.00]
 [40.00 61000.00]
 [43.00 133000.00]
 [59.00 76000.00]
 [60.00 42000.00]
 [39.00 106000.00]
 [57.00 26000.00]
 [57.00 74000.00]
 [38.00 71000.00]
 [49.00 88000.00]
 [52.00 38000.00]
 [50.00 36000.00]
 [59.00 88000.00]
 [35.00 61000.00]
 [37.00 70000.00]
 [52.00 21000.00]
 [48.00 141000.00]
 [37.00 93000.00]
 [37.00 62000.00]
 [48.00 138000.00]
 [41.00 79000.00]
 [37.00 78000.00]
 [39.00 134000.00]
 [49.00 89000.00]
 [55.00 39000.00]
 [37.00 77000.00]
 [35.00 57000.00]
 [36.00 63000.00]
 [42.00 73000.00]
 [43.00 112000.00]
 [45.00 79000.00]
 [46.00 117000.00]
 [58.00 38000.00]
 [48.00 74000.00]
 [37.00 137000.00]
 [37.00 79000.00]
 [40.00 60000.00]
 [42.00 54000.00]
 [51.00 134000.00]
 [47.00 113000.00]
 [36.00 125000.00]
 [38.00 50000.00]
 [42.00 70000.00]
 [39.00 96000.00]
 [38.00 50000.00]
 [49.00 141000.00]
 [39.00 79000.00]
 [39.00 75000.00]
 [54.00 104000.00]
 [35.00 55000.00]
 [45.00 32000.00]
 [36.00 60000.00]
 [52.00 138000.00]
 [53.00 82000.00]
 [41.00 52000.00]
 [48.00 30000.00]
 [48.00 131000.00]
 [41.00 60000.00]
 [41.00 72000.00]
 [42.00 75000.00]
 [36.00 118000.00]
 [47.00 107000.00]
 [38.00 51000.00]
 [48.00 119000.00]
 [42.00 65000.00]
 [40.00 65000.00]
 [57.00 60000.00]
 [36.00 54000.00]
 [58.00 144000.00]
 [35.00 79000.00]
 [38.00 55000.00]
 [39.00 122000.00]
 [53.00 104000.00]
 [35.00 75000.00]
 [38.00 65000.00]
 [47.00 51000.00]
 [47.00 105000.00]
 [41.00 63000.00]
 [53.00 72000.00]
 [54.00 108000.00]
 [39.00 77000.00]
 [38.00 61000.00]
 [38.00 113000.00]
 [37.00 75000.00]
 [42.00 90000.00]
 [37.00 57000.00]
 [36.00 99000.00]
 [60.00 34000.00]
 [54.00 70000.00]
 [41.00 72000.00]
 [40.00 71000.00]
 [42.00 54000.00]
 [43.00 129000.00]
 [53.00 34000.00]
 [47.00 50000.00]
 [42.00 79000.00]
 [42.00 104000.00]
 [59.00 29000.00]
 [58.00 47000.00]
 [46.00 88000.00]
 [38.00 71000.00]
 [54.00 26000.00]
 [60.00 46000.00]
 [60.00 83000.00]
 [39.00 73000.00]
 [59.00 130000.00]
 [37.00 80000.00]
 [46.00 32000.00]
 [46.00 74000.00]
 [42.00 53000.00]
 [41.00 87000.00]
 [58.00 23000.00]
 [42.00 64000.00]
 [48.00 33000.00]
 [44.00 139000.00]
 [49.00 28000.00]
 [57.00 33000.00]
 [56.00 60000.00]
 [49.00 39000.00]
 [39.00 71000.00]
 [47.00 34000.00]
 [48.00 35000.00]
 [48.00 33000.00]
 [47.00 23000.00]
 [45.00 45000.00]
 [60.00 42000.00]
 [39.00 59000.00]
 [46.00 41000.00]
 [51.00 23000.00]
 [50.00 20000.00]
 [36.00 33000.00]
 [49.00 36000.00]]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Nº Serie Motor          400 non-null    int64
 1   Par Carga (N.m)         400 non-null    float64
 2   RPM (Revoluciones/min)  400 non-null    float64
 3   Fallo Motor             400 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 12.6 KB

   Nº Serie Motor  Par Carga (N.m)  RPM (Revoluciones/min)  Fallo Motor
0        15624510             19.0                 19000.0            0
1        15810944             35.0                 20000.0            0
2        15668575             26.0                 43000.0            0
3        15603246             27.0                 57000.0            0
4        15804002             19.0                 76000.0            0
5        15728773             27.0                 58000.0            0
6        15598044             27.0                 84000.0            0
7        15694829             32.0                150000.0            1
8        15600575             25.0                 33000.0            0
9        15727311             35.0                 65000.0            0

## Data preprocessing and Data cleaning (Not required)
#### - No missing data (NaN).
#### - No categorical data.
#### - No dummy data.

## Split data into training/testing sets

In [ ]:
#Split data into training/testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Variable scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train_sc = sc_X.fit_transform(X_train)
X_test_sc = sc_X.transform(X_test)
np.set_printoptions(formatter=None)
print(X_train_sc)
print(X_test_sc)

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30684411]
 [ 0.08648817  0.76590222]
 [-1.00286662  0.56295021]
 [ 0.28455268  0.07006676]
 [ 0.68068169 -1.26361786]
 [-0.50770535 -0.01691267]
 [-1.79512465  0.35999821]
 [-0.70576986  0.12805305]
 [ 0.38358493  0.30201192]
 [-0.30964085  0.07006676]
 [-0.50770535  2.30253886]
 [ 0.18552042  0.04107362]
 [ 1.27487521  2.21555943]
 [ 0.77971394  0.27301877]
 [-0.30964085  0.1570462 ]
 [-0.01254409 -0.53878926]
 [-0.21060859  0.1570462 ]
 [-0.11157634  0.24402563]
 [-0.01254409 -0.24885782]
 [ 2.1661655   1.11381995]
 [-1.79512465  0.35999821]
 [ 1.86906873  0.12805305]
 [ 0.38358493 -0.13288524]
 [-1.20093113  0.30201192]
 [ 0.77971394  1.37475825]
 [-0.30964085 -0.24885782]
 [-1.6960924  -0.04590581]
 [-1.00286662 -0.74174127]
 [ 0.28455268  0.50496393]
 [-0.11157634 -1.06066585]
 [-1.10189888  0.59194336]
 [ 0.08648817 -0.79972756]
 [-1.00286662  1.54871711]
 [-0.70576986  1.40375139]
 [-1.29996338  0.50496393]
 [-0.30964085  0.04107362]
 [-0.11157634  0.01208048]
 [-0.30964085 -0.88670699]
 [ 0.8787462  -1.3505973 ]
 [-0.30964085  2.24455257]
 [ 0.97777845  1.98361427]
 [-1.20093113  0.47597078]
 [-1.29996338  0.27301877]
 [ 1.37390747  1.98361427]
 [ 1.27487521 -1.3505973 ]
 [-0.30964085 -0.27785096]
 [-0.50770535  1.25878567]
 [-0.80480212  1.08482681]
 [ 0.97777845 -1.06066585]
 [ 0.28455268  0.30201192]
 [ 0.97777845  0.76590222]
 [-0.70576986 -1.49556302]
 [-0.70576986  0.04107362]
 [ 0.48261718  1.72267598]
 [ 2.06713324  0.18603934]
 [-1.99318916 -0.74174127]
 [-0.21060859  1.40375139]
 [ 0.38358493  0.59194336]
 [ 0.8787462  -1.14764529]
 [-1.20093113 -0.77073441]
 [ 0.18552042  0.24402563]
 [ 0.77971394 -0.30684411]
 [ 2.06713324 -0.79972756]
 [ 0.77971394  0.12805305]
 [-0.30964085  0.6209365 ]
 [-1.00286662 -0.30684411]
 [ 0.18552042 -0.3648304 ]
 [ 2.06713324  2.12857999]
 [ 1.86906873 -1.26361786]
 [ 1.37390747 -0.91570013]
 [ 0.8787462   1.25878567]
 [ 1.47293972  2.12857999]
 [-0.30964085 -1.23462472]
 [ 1.96810099  0.91086794]
 [ 0.68068169 -0.71274813]
 [-1.49802789  0.35999821]
 [ 0.77971394 -1.3505973 ]
 [ 0.38358493 -0.13288524]
 [-1.00286662  0.41798449]
 [-0.01254409 -0.30684411]
 [-1.20093113  0.41798449]
 [-0.90383437 -1.20563157]
 [-0.11157634  0.04107362]
 [-1.59706014 -0.42281668]
 [ 0.97777845 -1.00267957]
 [ 1.07681071 -1.20563157]
 [-0.01254409 -0.13288524]
 [-1.10189888 -1.52455616]
 [ 0.77971394 -1.20563157]
 [ 0.97777845  2.07059371]
 [-1.20093113 -1.52455616]
 [-0.30964085  0.79489537]
 [ 0.08648817 -0.30684411]
 [-1.39899564 -1.23462472]
 [-0.60673761 -1.49556302]
 [ 0.77971394  0.53395707]
 [-0.30964085 -0.33583725]
 [ 1.77003648 -0.27785096]
 [ 0.8787462  -1.03167271]
 [ 0.18552042  0.07006676]
 [-0.60673761  0.8818748 ]
 [-1.89415691 -1.40858358]
 [-1.29996338  0.59194336]
 [-0.30964085  0.53395707]
 [-1.00286662 -1.089659  ]
 [ 1.17584296 -1.43757673]
 [ 0.18552042 -0.30684411]
 [ 1.17584296 -0.74174127]
 [-0.30964085  0.07006676]
 [ 0.18552042  2.09958685]
 [ 0.77971394 -1.089659  ]
 [ 0.08648817  0.04107362]
 [-1.79512465  0.12805305]
 [-0.90383437  0.1570462 ]
 [-0.70576986  0.18603934]
 [ 0.8787462  -1.29261101]
 [ 0.18552042 -0.24885782]
 [-0.4086731   1.22979253]
 [-0.01254409  0.30201192]
 [ 0.38358493  0.1570462 ]
 [ 0.8787462  -0.65476184]
 [ 0.08648817  0.1570462 ]
 [-1.89415691 -1.29261101]
 [-0.11157634  0.30201192]
 [-0.21060859 -0.27785096]
 [ 0.28455268 -0.50979612]
 [-0.21060859  1.6067034 ]
 [ 0.97777845 -1.17663843]
 [-0.21060859  1.63569655]
 [ 1.27487521  1.8676417 ]
 [-1.10189888 -0.3648304 ]
 [-0.01254409  0.04107362]
 [ 0.08648817 -0.24885782]
 [-1.59706014 -1.23462472]
 [-0.50770535 -0.27785096]
 [ 0.97777845  0.12805305]
 [ 1.96810099 -1.3505973 ]
 [ 1.47293972  0.07006676]
 [-0.60673761  1.37475825]
 [ 1.57197197  0.01208048]
 [-0.80480212  0.30201192]
 [ 1.96810099  0.73690908]
 [-1.20093113 -0.50979612]
 [ 0.68068169  0.27301877]
 [-1.39899564 -0.42281668]
 [ 0.18552042  0.1570462 ]
 [-0.50770535 -1.20563157]
 [ 0.58164944  2.01260742]
 [-1.59706014 -1.49556302]
 [-0.50770535 -0.53878926]
 [ 0.48261718  1.83864855]
 [-1.39899564 -1.089659  ]
 [ 0.77971394 -1.37959044]
 [-0.30964085 -0.42281668]
 [ 1.57197197  0.99784738]
 [ 0.97777845  1.43274454]
 [-0.30964085 -0.48080297]
 [-0.11157634  2.15757314]
 [-1.49802789 -0.1038921 ]
 [-0.11157634  1.95462113]
 [-0.70576986 -0.33583725]
 [-0.50770535 -0.8287207 ]
 [ 0.68068169 -1.37959044]
 [-0.80480212 -1.58254245]
 [-1.89415691 -1.46656987]
 [ 1.07681071  0.12805305]
 [ 0.08648817  1.51972397]
 [-0.30964085  0.09905991]
 [ 0.08648817  0.04107362]
 [-1.39899564 -1.3505973 ]
 [ 0.28455268  0.07006676]
 [-0.90383437  0.38899135]
 [ 1.57197197 -1.26361786]
 [-0.30964085 -0.74174127]
 [-0.11157634  0.1570462 ]
 [-0.90383437 -0.65476184]
 [-0.70576986 -0.04590581]
 [ 0.38358493 -0.45180983]
 [-0.80480212  1.89663484]
 [ 1.37390747  1.28777882]
 [ 1.17584296 -0.97368642]
 [ 1.77003648  1.83864855]
 [-0.90383437 -0.24885782]
 [-0.80480212  0.56295021]
 [-1.20093113 -1.5535493 ]
 [-0.50770535 -1.11865214]
 [ 0.28455268  0.07006676]
 [-0.21060859 -1.06066585]
 [ 1.67100423  1.6067034 ]
 [ 0.97777845  1.78066227]
 [ 0.28455268  0.04107362]
 [-0.80480212 -0.21986468]
 [-0.11157634  0.07006676]
 [ 0.28455268 -0.19087153]
 [ 1.96810099 -0.65476184]
 [-0.80480212  1.3457651 ]
 [-1.79512465 -0.59677555]
 [-0.11157634  0.12805305]
 [ 0.28455268 -0.30684411]
 [ 1.07681071  0.56295021]
 [-1.00286662  0.27301877]
 [ 1.47293972  0.35999821]
 [ 0.18552042 -0.3648304 ]
 [ 2.1661655  -1.03167271]
 [-0.30964085  1.11381995]
 [-1.6960924   0.07006676]
 [-0.01254409  0.04107362]
 [ 0.08648817  1.05583366]
 [-0.11157634 -0.3648304 ]
 [-1.20093113  0.07006676]
 [-0.30964085 -1.3505973 ]
 [ 1.57197197  1.11381995]
 [-0.80480212 -1.52455616]
 [ 0.08648817  1.8676417 ]
 [-0.90383437 -0.77073441]
 [-0.50770535 -0.77073441]
 [-0.30964085 -0.91570013]
 [ 0.28455268 -0.71274813]
 [ 0.28455268  0.07006676]
 [ 0.08648817  1.8676417 ]
 [-1.10189888  1.95462113]
 [-1.6960924  -1.5535493 ]
 [-1.20093113 -1.089659  ]
 [-0.70576986 -0.1038921 ]
 [ 0.08648817  0.09905991]
 [ 0.28455268  0.27301877]
 [ 0.8787462  -0.5677824 ]
 [ 0.28455268 -1.14764529]
 [-0.11157634  0.67892279]
 [ 2.1661655  -0.68375498]
 [-1.29996338 -1.37959044]
 [-1.00286662 -0.94469328]
 [-0.01254409 -0.42281668]
 [-0.21060859 -0.45180983]
 [-1.79512465 -0.97368642]
 [ 1.77003648  0.99784738]
 [ 0.18552042 -0.3648304 ]
 [ 0.38358493  1.11381995]
 [-1.79512465 -1.3505973 ]
 [ 0.18552042 -0.13288524]
 [ 0.8787462  -1.43757673]
 [-1.99318916  0.47597078]
 [-0.30964085  0.27301877]
 [ 1.86906873 -1.06066585]
 [-0.4086731   0.07006676]
 [ 1.07681071 -0.88670699]
 [-1.10189888 -1.11865214]
 [-1.89415691  0.01208048]
 [ 0.08648817  0.27301877]
 [-1.20093113  0.33100506]
 [-1.29996338  0.30201192]
 [-1.00286662  0.44697764]
 [ 1.67100423 -0.88670699]
 [ 1.17584296  0.53395707]
 [ 1.07681071  0.53395707]
 [ 1.37390747  2.331532  ]
 [-0.30964085 -0.13288524]
 [ 0.38358493 -0.45180983]
 [-0.4086731  -0.77073441]
 [-0.11157634 -0.50979612]
 [ 0.97777845 -1.14764529]
 [-0.90383437 -0.77073441]
 [-0.21060859 -0.50979612]
 [-1.10189888 -0.45180983]
 [-1.20093113  1.40375139]]
[[-0.80480212  0.50496393]
 [-0.01254409 -0.5677824 ]
 [-0.30964085  0.1570462 ]
 [-0.80480212  0.27301877]
 [-0.30964085 -0.5677824 ]
 [-1.10189888 -1.43757673]
 [-0.70576986 -1.58254245]
 [-0.21060859  2.15757314]
 [-1.99318916 -0.04590581]
 [ 0.8787462  -0.77073441]
 [-0.80480212 -0.59677555]
 [-1.00286662 -0.42281668]
 [-0.11157634 -0.42281668]
 [ 0.08648817  0.21503249]
 [-1.79512465  0.47597078]
 [-0.60673761  1.37475825]
 [-0.11157634  0.21503249]
 [-1.89415691  0.44697764]
 [ 1.67100423  1.75166912]
 [-0.30964085 -1.37959044]
 [-0.30964085 -0.65476184]
 [ 0.8787462   2.15757314]
 [ 0.28455268 -0.53878926]
 [ 0.8787462   1.02684052]
 [-1.49802789 -1.20563157]
 [ 1.07681071  2.07059371]
 [-1.00286662  0.50496393]
 [-0.90383437  0.30201192]
 [-0.11157634 -0.21986468]
 [-0.60673761  0.47597078]
 [-1.6960924   0.53395707]
 [-0.11157634  0.27301877]
 [ 1.86906873 -0.27785096]
 [-0.11157634 -0.48080297]
 [-1.39899564 -0.33583725]
 [-1.99318916 -0.50979612]
 [-1.59706014  0.33100506]
 [-0.4086731  -0.77073441]
 [-0.70576986 -1.03167271]
 [ 1.07681071 -0.97368642]
 [-1.10189888  0.53395707]
 [ 0.28455268 -0.50979612]
 [-1.10189888  0.41798449]
 [-0.30964085 -1.43757673]
 [ 0.48261718  1.22979253]
 [-1.10189888 -0.33583725]
 [-0.11157634  0.30201192]
 [ 1.37390747  0.59194336]
 [-1.20093113 -1.14764529]
 [ 1.07681071  0.47597078]
 [ 1.86906873  1.51972397]
 [-0.4086731  -1.29261101]
 [-0.30964085 -0.3648304 ]
 [-0.4086731   1.31677196]
 [ 2.06713324  0.53395707]
 [ 0.68068169 -1.089659  ]
 [-0.90383437  0.38899135]
 [-1.20093113  0.30201192]
 [ 1.07681071 -1.20563157]
 [-1.49802789 -1.43757673]
 [-0.60673761 -1.49556302]
 [ 2.1661655  -0.79972756]
 [-1.89415691  0.18603934]
 [-0.21060859  0.85288166]
 [-1.89415691 -1.26361786]
 [ 2.1661655   0.38899135]
 [-1.39899564  0.56295021]
 [-1.10189888 -0.33583725]
 [ 0.18552042 -0.65476184]
 [ 0.38358493  0.01208048]
 [-0.60673761  2.331532  ]
 [-0.30964085  0.21503249]
 [-1.59706014 -0.19087153]
 [ 0.68068169 -1.37959044]
 [-1.10189888  0.56295021]
 [-1.99318916  0.35999821]
 [ 0.38358493  0.27301877]
 [ 0.18552042 -0.27785096]
 [ 1.47293972 -1.03167271]
 [ 0.8787462   1.08482681]
 [ 1.96810099  2.15757314]
 [ 2.06713324  0.38899135]
 [-1.39899564 -0.42281668]
 [-1.20093113 -1.00267957]
 [ 1.96810099 -0.91570013]
 [ 0.38358493  0.30201192]
 [ 0.18552042  0.1570462 ]
 [ 2.06713324  1.75166912]
 [ 0.77971394 -0.8287207 ]
 [ 0.28455268 -0.27785096]
 [ 0.38358493 -0.16187839]
 [-0.11157634  2.21555943]
 [-1.49802789 -0.62576869]
 [-1.29996338 -1.06066585]
 [-1.39899564  0.41798449]
 [-1.10189888  0.76590222]
 [-1.49802789 -0.19087153]
 [ 0.97777845 -1.06066585]
 [ 0.97777845  0.59194336]
 [ 0.38358493  0.99784738]]

### **First attempt: Create and fit a base SVM model**

In [ ]:
from sklearn import svm

model_svc = svm.SVC(kernel = "linear", probability=True, random_state = 0)
model_svc.fit(X_train_sc,y_train)
model_svc.score(X_test_sc, y_test)

0.9

In [ ]:
model_svc = svm.SVC(kernel = "rbf", probability=True, random_state = 0)
model_svc.fit(X_train_sc,y_train)
model_svc.score(X_test_sc, y_test)

0.93

### **Second attempt: Create and fit a basic Random Forest model**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators = 10, criterion = "entropy", random_state = 0)
model_rf.fit(X_train_sc, y_train)
model_rf.score(X_test_sc, y_test)

0.91

Not bad, pretty good results. But, how do we know if there is a better model?

and how do we tune the model's hyperparameters to get best accuracy?

### **Solution: Perform model and hyperparameters exhaustive search**

We need to perform an exhaustive model and parameters search to ensure best accuracy.

So, first, let's define the subset of models and parameters for each model where we will perform our search.

In [ ]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# define model dictionary
# liblinear: es un optimizador para problemas de clasificacion binaria. No funciona con multiclase
# gamma
#  - Gamma alto: Cada punto influye solo en su entorno inmediato, generando fronteras de decisión (plano de corte) muy complejas y riesgo de sobreajuste.
#  - Gamma bajo: La influencia de cada punto se extiende más, produciendo fronteras de decisión suaves y mayor capacidad de generalización.
models = {
    'LogisticRegression': LogisticRegression(solver='liblinear',multi_class='auto', random_state = 0 ),
    'RandomForestClassifier': RandomForestClassifier(criterion = "entropy", random_state = 0 ),
    'SVM' : svm.SVC(gamma='auto', random_state = 0 )
}
# define parameters dictionary
params = {
    'LogisticRegression': { 'C': [1, 5, 10] },
    'RandomForestClassifier': { 'n_estimators': [1, 5, 10] },
    'SVM' : { 'C': [1,10,20], 'kernel': ['rbf','linear'] }
}

Just for sanity, let's ensure that the dictionaries are well defined:

In [ ]:
models.keys()

dict_keys(['LogisticRegression', 'RandomForestClassifier', 'SVM'])

In [ ]:
models.values()

dict_values([LogisticRegression(multi_class='auto', random_state=0, solver='liblinear'), RandomForestClassifier(criterion='entropy', random_state=0), SVC(gamma='auto', random_state=0)])

In [ ]:
# then, retrieving the value for a given key:
models['LogisticRegression']

LogisticRegression(multi_class='auto', random_state=0, solver='liblinear')

Finally, we can use `GridSearchCV`, that will fit every model with all possible combinations of parameters to check which one gives better results. This of course can be computing intensive task.

In [ ]:
from sklearn.model_selection import GridSearchCV

scores = []

for i in models.keys():
    clf =  GridSearchCV(models[i], params[i], cv=5, return_train_score=False)
    clf.fit(X_train_sc, y_train)
    scores.append({
        'model': models[i],
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

# return_train_score=False:
# - Especifica que no se almacenarán ni devolverán los puntajes (scores) del conjunto de entrenamiento en los resultados de la búsqueda.

# - ¿Qué significa?
#     Esto ayuda a ahorrar memoria y tiempo, ya que solo se almacenarán los puntajes de validación (los que se obtienen en cada pliegue de la validación cruzada) y no los del entrenamiento.
# - ¿Por qué podría ser útil?
#     Si solo te interesa evaluar la capacidad de generalización del modelo y no necesitas analizar cómo se comportó durante el entrenamiento, puedes establecerlo en False.

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [ ]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

,model,best_score,best_params
0,"LogisticRegression(multi_class='auto', random_...",0.826667,{'C': 1}
1,"RandomForestClassifier(criterion='entropy', ra...",0.893333,{'n_estimators': 10}
2,"SVC(gamma='auto', random_state=0)",0.903333,"{'C': 1, 'kernel': 'rbf'}"

To reduce processing time, we could instead use `RandomizedSearchCV` that fits just a subset of random combinations of parameters.

**Combinación aleatoria de hyperparametros vs combinación exahustiva**

En el caso anterior se va a realizar una busqueda exahustiva, combinando todos los hyperparametros con todos. Imaginad el caso de un dataset con 1.000.000 datos, donde queremos evaluar 100 hyperparámetros con 5 modelos diferentes, en este caso el GridSearch podria tardar una semana.

Solucion: RandomizedSearchCV, donde haremos una selección aleatoria de combinación de hyperparámetros.

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

scores = []

for i in models.keys():
    clf =  RandomizedSearchCV(models[i], params[i], cv=5, return_train_score=False, n_iter=3)
    clf.fit(X_train_sc, y_train)
    scores.append({
        'model': models[i],
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [ ]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

,model,best_score,best_params
0,"LogisticRegression(multi_class='auto', random_...",0.826667,{'C': 1}
1,"RandomForestClassifier(criterion='entropy', ra...",0.893333,{'n_estimators': 10}
2,"SVC(gamma='auto', random_state=0)",0.903333,"{'kernel': 'rbf', 'C': 20}"